### ISSUE TITLE
No way to make the VST3 or the .component work in Ableton

### ISSUE THREAD

**Issue by stewartsisas** [Torsion-Audio/Scyclone#6]
I have a macbook m1 with Ableton 10. The VST3 and .component doesn't get recognized by the DAW. Even if I try Intel versions, those don't work either.

The standalone version seems to work, but I want use it inside my DAW.

**Comment by faressc** [comment]
Hi thanks for reporting. Which Scyclone version are you using? The latest Scyclone-v.0.0.3-osx-arm64.dmg? In which folder did you copy the VST3 or .component?

**Comment by stewartsisas** [comment]
I tried with the last two versions, and I copied them in the correct folder, along the rest of my vst. Ableton never recognized them, the standalone worked, but that's not what I wanted. As far I know it's a very common bug in Mac.

**Comment by faressc** [comment]
The v0.0.2 will not work because they are not notarised, so better stick with the v0.0.3. I assume you also rescanned for plug-ins in the preferences... Did you put it in the VST3 folder of your mac? Because it won't work if you put it in the VST folder along with VST1 or 2 plug-ins (if you use the VST3 Plug-In System folders in Ableton)...

**Comment by stewartsisas** [comment]
All of that, I did. Nothing.

Check this video, the guy has the same problem, he even had to find a weird DAW to make it work.

https://youtu.be/Towyb5ILwWc

**Comment by faressc** [comment]
By the time the video was released, only the v0.0.2 was uploaded. Also he uses windows I believe. Version v0.0.3 has been actually tested on M1 and Ableton.

Could you make a screenshot from your Ableton plug-in preferences and sent me the folder path the plug-in is in. I don't know what else could be the issue... It is not showing up at all right?

**Comment by stewartsisas** [comment]
Hey, thanks for the support. Sure here is the images, and the guy in the video says he never could make it work in Mac, ultimately he makes it work in that weird Windows DAW.
![Screen Shot 2023-06-26 at 13 46 21](https://github.com/Torsion-Audio/Scyclone/assets/137734412/a42816ee-4bd6-4c24-a4f3-a8313249d91e)
![Screen Shot 2023-06-26 at 13 47 02](https://github.com/Torsion-Audio/Scyclone/assets/137734412/6040fd4b-1e22-4ae4-a250-045393875039)
![Screen Shot 2023-06-26 at 13 48 13](https://github.com/Torsion-Audio/Scyclone/assets/137734412/47ed5805-8828-45c9-809c-5be5182615f4)
![Screen Shot 2023-06-26 at 13 49 24](https://github.com/Torsion-Audio/Scyclone/assets/137734412/0530f71e-7d2e-4c3b-bcde-883891ec0713)
![Screen Shot 2023-06-26 at 13 53 04](https://github.com/Torsion-Audio/Scyclone/assets/137734412/fb673ed1-0734-4f14-a24d-896484efc6d5)

**Comment by stewartsisas** [comment]
> By the time the video was released, only the v0.0.2 was uploaded. Also he uses windows I believe. Version v0.0.3 has been actually tested on M1 and Ableton.
> 
>  I don't know what else could be the issue... It is not showing up at all right?

Well checking Reddit, seems like your VST3 only works in Ableton 11. That's a shame, not everyone should be forced to upgrade the DAW, I'm very confortable on the 10.

**Comment by faressc** [comment]
Hi,

thank you for your help! It's great to have people reporting issues, so that we can track them down.

Looks like the paths are all right.

Could you open the terminal and report back the output if you run the following two commands:

```codesign -dv --verbose=4 path/to/Scyclone.vst3```

And 

```spctl -a -vvv -t install path/to/Scyclone.vst3```

This way we can check if the notarisation has been found...

**Comment by faressc** [comment]
> Well checking Reddit, seems like your VST3 only works in Ableton 11. That's a shame, not everyone should be forced to upgrade the DAW, I'm very confortable on the 10. 
> 
> 
> 
> 

Could you also send me the link to this discussion? I was not aware of this one...

**Comment by stewartsisas** [comment]
This is on Reddit: https://www.reddit.com/r/abletonlive/comments/14j0yx3/can_somebody_tell_me_how_to_make_this_vst_work/

**Comment by faressc** [comment]
Cool thanks for sharing :)
I think I have figured out the issue. Ableton 10 runs in Rosetta. This means it is an intel x64 application that does not support native apple silicon binaries. In order to make Scyclone work, you will need to download the [Scyclone-v.0.0.3-osx-x64.dmg](https://github.com/Torsion-Audio/Scyclone/releases/download/v.0.0.3/Scyclone-v.0.0.3-osx-x64.dmg) build. Since Ableton 11.1 they have a universal build that supports both running Ableton native and via rosetta. In case you run Ableton 11 native you will need the [Scyclone-v.0.0.3-osx-arm64.dmg](https://github.com/Torsion-Audio/Scyclone/releases/download/v.0.0.3/Scyclone-v.0.0.3-osx-arm64.dmg) version, in case you run Ableton 11 via rosetta, because you have other x64 plugins for example, you will need to download the [Scyclone-v.0.0.3-osx-x64.dmg](https://github.com/Torsion-Audio/Scyclone/releases/download/v.0.0.3/Scyclone-v.0.0.3-osx-x64.dmg) build.

Anyway in your case you would need to download the [Scyclone-v.0.0.3-osx-x64.dmg](https://github.com/Torsion-Audio/Scyclone/releases/download/v.0.0.3/Scyclone-v.0.0.3-osx-x64.dmg), put it in the right directory and hopefully it works :) I have just tested it on an M1 with Ableton 10 and it worked... Please let me know if this works for you, too.

**Comment by stewartsisas** [comment]
Finally is working!

**Comment by stewartsisas** [comment]
Works

**Comment by faressc** [comment]
Great thanks for reporting back :) Have fun with the plugin and stay tuned, the next major release is coming soon!
